#!/usr/bin/env bash

# -------------------- [ gera ruby script ] ----------------------+
#        Script   : rubyscript                                    |
#        Author   : Jesher Minelli <jesherdevsk8@gmail.com>       |
#        Date     : seg 15 ago 2022                               |  
# ----------------------------------------------------------------+

editor="vim"
dia_de_hoje=$(date +"%a %e %h %Y")
header="#!/usr/bin/env ruby
# Jesher Minelli <jesherdevsk8@gmail.com> - $dia_de_hoje
"

#--------------------------- TESTES -------------------------------

# Testar se o arquivo já existe
[[ -f $1 ]] && echo "Arquivo já existente! Saindo....." && exit 1 #arquivo existe?

# Testar se o usuario passou o número certo de
# argumentos ...... (1 argumento)
[[ $# -ne 1 ]] && echo "Eu preciso de *um* nome de arquivo" && exit 1 # Passou um argumento?

#---------------------------- MAIN --------------------------------

echo "$header" > $1
chmod +x $1
$editor $1

exit 0
